earntype,employeecategory,grademaster,earnings/deduction
itmedicity/inteliqo pull request #5
Opened 2021-11-06 11:34 UTC by ReshmaRaj1994

2021-11-06 11:47 UTC, itmedicity requested changes

2021-11-06 11:47 UTC, itmedicity commented on src/views/Master/EarningDeductionMaster/EarnDectEdit.jsx
> +    const deful = {
unidentified Name

2021-11-06 11:47 UTC, itmedicity commented on src/views/Master/EmploymentType/EmploymentTypetable.jsx
> -        const { emt_slno } = data;
Repeated Destructuring

2021-11-06 11:47 UTC, itmedicity commented on src/views/Master/GradeMaster/GradeMastEdit.jsx
> +
Remove the Unwanted Space

2021-11-08 04:11 UTC, ReshmaRaj1994 commented on src/views/Master/EmploymentType/EmploymentTypetable.jsx
> -        const { emt_slno } = data;
ok

2021-11-08 04:11 UTC, ReshmaRaj1994 commented on src/views/Master/GradeMaster/GradeMastEdit.jsx
> +
ok

2021-11-08 04:11 UTC, ReshmaRaj1994 commented on src/views/Master/EarningDeductionMaster/EarnDectEdit.jsx
> +    const deful = {
ok

2021-11-08 04:12 UTC, closed without merging